tfc_organization           = "hashi-demos-apj"
github_organization        = "hashicorp-demo-lab"
tfc_project                = "Default Project"
tfc_workspace              = "aws-dynamic-credentials"
VAULT_PATH                 = "aws-dynamic-credentials"
region                     = "ap-southeast-2"