tfc_organization           = "hashi-demos-apj"
github_organization        = "hashicorp-demo-lab"
tfc_project                = "Default Project"
tfc_workspace              = "aws-dynamic-credentials"
#role_arns                  = "arn:aws:iam::258850230659:role/testrole"
VAULT_PATH                 = "aws-dynamic-credentials"
region                     = "ap-southeast-2"
doormat_user_arn = "arn:aws:sts::855831148133:assumed-role/aws_simon.lynch_test-developer/simon.lynch@hashicorp.com"