tfc_organization           = "hashi-demos-apj"
tfc_project                = "Default Project"
tfc_workspace              = "aws-infra"
kv_secrets_mount           = "demo-key-value"
kv_secrets_key             = "pipelines_secrets"
role_arns                  = "arn:aws:iam::258850230659:role/testrole"
VAULT_PATH                 = "demo-aws-dynamic-credentials"
region                     = "ap-southeast-2"
