
@tf_cloud=app.terraform.io
@ORG_NAME=hashi-demos-apj
@token=
@org_token=
@workspace_id=
@run_id=

## Get Workspace by Name;
GET https://{{tf_cloud}}/api/v2/organizations/{{ORG_NAME}}/workspaces/aws-future-app HTTP/1.1
Authorization: Bearer {{token}}

### Get a User example
GET https://{{tf_cloud}}/api/v2/users/user-BFWHxa8UmcyQVhk1
Authorization: Bearer {{token}}

### Get a users Authentication tokens 

GET https://{{tf_cloud}}/api/v2/users/user-BFWHxa8UmcyQVhk1/authentication-tokens
Authorization: Bearer {{token}}
###


### Get Teams
GET https://{{tf_cloud}}/api/v2/organizations/{{ORG_NAME}}/teams
Authorization: Bearer {{token}}
###
## Get Audit logs
GET https://{{tf_cloud}}/api/v2/organization/audit-trail
Authorization: Bearer {{org_token}}


###
## Get Workspace by Id
GET https://{{tf_cloud}}/api/v2/workspaces/ws-JAGLNVyogairr22o
Authorization: Bearer {{token}}

###
GET https://{{tf_cloud}}/api/v2/workspaces/ws-JAGLNVyogairr22o/configuration-versions
Authorization: Bearer {{token}}

###


POST https://{{tf_cloud}}/api/v2/workspaces/ws-JAGLNVyogairr22o/configuration-versions HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "configuration-versions",
    "attributes": {
    }
  }
}

###
## Get Workspace Runs
GET https://{{tf_cloud}}/api/v2/workspaces/{{workspace_id}}/runs/
Authorization: Bearer {{token}}

###
## List Policy Checks
GET https://{{tf_cloud}}/api/v2/runs/{{run_id}}/policy-checks
Authorization: Bearer {{token}}
