@vault_host=localhost:8200
@username=
@password=root
@auth_method=token
@path=demo-key-value
@secret_key=aarons-secrets
#@authToken = {{login.response.body.auth.client_token}}
@authToken = root
## Authenticate to Vault with userpass method;

# @name login
POST http://{{vault_host}}/v1/auth/{{auth_method}}/login/{{username}}
Accept: application/json
Content-Type: application/json

{"password": "{{password}}" }

###
## Get Secrets

GET http://{{vault_host}}/v1/{{path}}/data/{{secret_key}}
X-Vault-Token: {{authToken}}
