tfc_organization           = "hashi-demos-apj"
github_organization        = "hashicorp-demo-lab"
tfc_project                = "Default Project"
tfc_workspace              = "aws-dynamic-credentials"
role_arns                  = "arn:aws:iam::258850230659:role/testrole"
VAULT_PATH                 = "aws-dynamic-credentials"
region                     = "ap-southeast-2"
doormat_user_arn           = "arn:aws:sts::258850230659:assumed-role/aws_aaron.evans_test-developer/aaron.evans@hashicorp.com"